### ISSUE TITLE
Migrate into typescript

### ISSUE THREAD

**Issue by SamX23** [SamX23/group-chat-app#1]
I'm going to list the components one by one to migrate

- [ ] Initializing typescript
- [ ] StateProvider
- [ ] App component
- [ ] Login page
- [ ] Sidebar component
- [ ] Chat + sidebar chat component

Feel free to create new issue for each component and mention me to assign your username.

**Comment by kfnx** [comment]
why?

**Comment by SamX23** [comment]
> why?

I wanted to use it on this repo, it is simpler, typechecking by default, and good looking. 
Any suggestions will be great.
