### ISSUE TITLE
Adding firebase auth persistence

### ISSUE THREAD

**Issue by SamX23** [SamX23/group-chat-app#4]
Im a bit stuck on adding auth persistence so users no need to re login after refreshing the page.

**Comment by Conor-Hinchee** [comment]
@SamX23 I would like to help with this

**Comment by SamX23** [comment]
Sure, thank you :)

**Comment by SamX23** [comment]
Thanks @captnstarburst , now  I have applied the ux issue using [this](https://www.robinwieruch.de/react-firebase-auth-persistence) :)
